REPLACE INTO `role` VALUES (1,'USER');
REPLACE INTO `role` VALUES (2,'ADMIN');
DROP TRIGGER IF EXISTS update_Company_insert_creationdate;
DROP TRIGGER IF EXISTS update_Company_update_creationdate;
DROP TRIGGER IF EXISTS update_account_insert_creationdate;
DROP TRIGGER IF EXISTS update_account_update_creationdate;
DROP TRIGGER IF EXISTS update_payment_insert_creationdate;
DROP TRIGGER IF EXISTS update_payment_update_creationdate;
DROP TRIGGER IF EXISTS update_receipt_insert_creationdate;
DROP TRIGGER IF EXISTS update_receipt_update_creationdate;
DROP TRIGGER IF EXISTS update_user_insert_creationdate;
DROP TRIGGER IF EXISTS update_user_update_creationdate;
DROP TRIGGER IF EXISTS update_invoice_insert_creationdate;
DROP TRIGGER IF EXISTS update_invoice_update_creationdate;
CREATE TRIGGER update_Company_insert_creationdate BEFORE INSERT ON company_details FOR EACH ROW SET NEW.company_creation_date = NOW();
CREATE TRIGGER update_Company_update_creationdate BEFORE UPDATE ON company_details FOR EACH ROW SET NEW.company_creation_date = OLD.company_creation_date, NEW.company_last_modified = NOW();
CREATE TRIGGER update_account_insert_creationdate BEFORE INSERT ON account_details FOR EACH ROW SET NEW.account_creation_date = NOW();
CREATE TRIGGER update_account_update_creationdate BEFORE UPDATE ON account_details FOR EACH ROW SET NEW.account_creation_date = OLD.account_creation_date;
CREATE TRIGGER update_payment_insert_creationdate BEFORE INSERT ON payment_details FOR EACH ROW SET NEW.payment_creation_date = NOW();
CREATE TRIGGER update_payment_update_creationdate BEFORE UPDATE ON payment_details FOR EACH ROW SET NEW.payment_creation_date = OLD.payment_creation_date;
CREATE TRIGGER update_receipt_insert_creationdate BEFORE INSERT ON receipt_details FOR EACH ROW SET NEW.receipt_creation_date = NOW();
CREATE TRIGGER update_receipt_update_creationdate BEFORE UPDATE ON receipt_details FOR EACH ROW SET NEW.receipt_creation_date = OLD.receipt_creation_date;
CREATE TRIGGER update_user_insert_creationdate BEFORE INSERT ON user FOR EACH ROW SET NEW.user_creation_date = NOW();
CREATE TRIGGER update_user_update_creationdate BEFORE UPDATE ON user FOR EACH ROW SET NEW.user_creation_date = OLD.user_creation_date;
CREATE TRIGGER update_invoice_insert_creationdate BEFORE INSERT ON invoice_details FOR EACH ROW SET NEW.invoice_creation_date = NOW();
CREATE TRIGGER update_invoice_update_creationdate BEFORE UPDATE ON invoice_details FOR EACH ROW SET NEW.invoice_creation_date = OLD.invoice_creation_date;